
CREATE TABLE TBL_RESULT (
 TICKER VARCHAR(6),
 LAST_CLOSE NUMERIC(10,2),
 PURCHASE_DATE DATE,
 SECTOR VARCHAR(30),
 PURCHASE_PRICE NUMERIC(10,2),
 PURCHASE_VOL INT,
 PNL NUMERIC(10,2),
 CREATE_DATE TIMESTAMP
);


CREATE INDEX tbl_result on tbl_result (ticker, sector, purchase_date);


CREATE TABLE TBL_SCHEMA (
FILE_NAME VARCHAR(100),
COL_NAME VARCHAR(100),
COL_TYPE_SUGGEST VARCHAR(20),
COL_TYPE_FINAL VARCHAR(20),
USER_ID VARCHAR(10),
CREATE_DATE TIMESTAMP);
